---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
            context: org-global
