---
version: 2
jobs:
  build:
    docker:
      - image: rwlaub/api:latest
        auth:
          username: rwlaub
          password: $DOCKERHUB_PASSWORD
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
            context: org-global
